#!/system/bin/sh
#MMS Config by Team Venom
#Do not use without permission.
#This script will set the MMS values based on the values in default.xml
echo "95mmsconfig"

DefaultMMSConfig="/system/customize/MNS/default.xml"
MMSCustomizationsFile="/data/data/com.android.mms/shared_prefs/com.android.mms.customizationBySIM.xml"
MMSPreferences="/data/data/com.android.mms/shared_prefs/com.android.mms_preferences.xml"

getXmlValue()
{
   if [ -f $2 ]; then
      #echo "Getting $1 from $2"
      #echo "sed -n -e \"s/.*<item name=\"$1\">\(.*\)<\/item>.*/\1/p\" $2"
      sed -n -e "s/.*<item name=\"$1\">\(.*\)<\/item>.*/\1/p" $2
      #echo $Output
   #else
      #echo "Can't find file to get value from: $2"
   fi
}

updateXmlValue()
{
   if [ -f $3 ]; then
      if [ -n "$2" ]; then
         echo "Updating $3: $1=$2"
         sed -i "s/.*$1.*/<string name=\"$1\">$2<\/string>/" $3
      else
         echo "Value is blank: $2"
      fi
   else
      echo "Can't find file to update: $3"
   fi
}

if [ -f $DefaultMMSConfig -a -f $MMSCustomizationsFile -a -f $MMSPreferences ]; then
   MMS_Msg_Size1=$(getXmlValue "MMS_Msg_Size1" "$DefaultMMSConfig")
   updateXmlValue "MMS_Msg_Size1" "$MMS_Msg_Size1" "$MMSCustomizationsFile"

   MMS_Msg_Size2=$(getXmlValue "MMS_Msg_Size2" "$DefaultMMSConfig")
   updateXmlValue "MMS_Msg_Size2" "$MMS_Msg_Size2" "$MMSCustomizationsFile"

   MMS_Msg_Size3=$(getXmlValue "MMS_Msg_Size3" "$DefaultMMSConfig")
   updateXmlValue "MMS_Msg_Size3" "$MMS_Msg_Size3" "$MMSCustomizationsFile"

   MMS_Msg_Size_Choose=$(getXmlValue "MMS_Msg_Size_Choose" "$DefaultMMSConfig")

   echo "MMS Size Choose: $MMS_Msg_Size_Choose"
   case "$MMS_Msg_Size_Choose" in
      $MMS_Msg_Size1)
         default=1
      ;;
      $MMS_Msg_Size2)
         default=2
      ;;
      $MMS_Msg_Size3)
         default=3
      ;;
      *)
         default=1
      ;;
   esac

   #updateXmlValue "MMS_Msg_Size_Choose" "$default" "$MMSCustomizationsFile"
   #updateXmlValue "pref_key_mms_max_size" "$default" "$MMSPreferences"
else
   echo "Couldn't find all required files."
fi

echo "95mmsconfig Done."
